function NiceScroll(a){this.taId=a;this.ta=id(this.taId);if(1!=this.ta.nodeType)return null;this.st=el("label");this.sb=el("div");this.sbcH=this.avg=this.stH=this.scH=this.sbH=0;this.n=20;this.enabled=!0;this.mousePos=null;this.show=this.onSb=this.isScroll=!1;this.wtId=this.checkTt=null;this.woSpeed=this.wSpeed=this.wtCounter=0;this.sbStyle={position:"absolute",zIndex:1001,width:"0.583em",mTop:0,mLeft:0};this.stStyle={width:"0.583em",display:"inline-block",background:"#9FE3D1",borderRadius:"3px",
position:"relative",cursor:"pointer"};this.stOpacity=0.1;"function"!=typeof this.init&&(NiceScroll.prototype.init=function(){var a=this;this.sb.id=this.taId+"niceScrollSb"+(new Date).getTime();setStyle(this.sb,{backgroundColor:this.sbStyle.background||"transparent"});this.sb.appendChild(this.st);document.body.appendChild(this.sb);setStyle(this.sb,this.sbStyle);setStyle(this.st,this.stStyle);this._reset();!1==OS.portable?setStyle(this.ta,{overflow:"hidden"}):setStyle(this.ta,{overflow:"scroll"});this._shSb();
this._bind();window.setTimeout(function(){a.checkTt=window.setTimeout(arguments.callee,10);a._check()},100)},NiceScroll.prototype.scrollBarSet=function(a){if("object"==typeof a)for(var c in a)this.sbStyle[c]=a[c]},NiceScroll.prototype.scrollTipSet=function(a){if("object"==typeof a)for(var c in a)this.stStyle[c]=a[c]},NiceScroll.prototype.scrollTipOpacity=function(a){this.stOpacity=a},NiceScroll.prototype.scrollTo=function(a){a=parseInt(a);if(!0==isNaN(a))return!1;this.ta.scrollTop=a},NiceScroll.prototype._reset=
function(){var a=getoffset(this.ta),c=this.ta.offsetWidth,d=this.ta.offsetHeight-this.sbStyle.mTop,e=this.ta.scrollHeight-this.sbStyle.mTop,f=parseFloat(getNodeDefaultView(this.ta,"borderTopWidth"))||0,g=parseFloat(getNodeDefaultView(this.ta,"borderBottomWidth"))||0,h=parseFloat(getNodeDefaultView(this.ta,"borderRightWidth"))||0;parseFloat(getNodeDefaultView(this.ta,"borderLeftWidth"));this.scH=e-d+f+g;this.stH=parseInt(0.7*(d/e)*d);this.sbcH=d-(this.stH+2);this.avg=this.scH/this.sbcH;0>=e-d?(setStyle(this.sb,
{visibility:"hidden"}),this.show=!1):(this.show=!0,setStyle(this.sb,{visibility:"visible"}),setStyle(this.sb,{top:a.top+f+this.sbStyle.mTop+"px",height:d+"px",left:a.left-this.sbStyle.mLeft+c-h-parseInt(this.sb.offsetWidth)+"px"}),setStyle(this.st,{top:this.ta.scrollTop/this.scH*this.sbcH+"px",height:this.stH+"px"}))},NiceScroll.prototype._bind=function(){function a(b){b=b||window.event;var c=b.touches[0].clientY,g=c-d.mousePos.y,g=parseFloat(d.st.style.top)-g,g=g>=d.sbcH?d.sbcH:0>=g?0:g;d.st.style.top=
g+"px";d.mousePos.y=c;d.isScroll=!0;!1==OS.portable&&(d.ta.scrollTop=d.scH*(g/d.sbcH),eventPreventDefault(b));clearSelection(b)}function c(e){detachEvnt(document,"touchmove",a);detachEvnt(document,"touchend",c);!1==d.onSb&&(d.isScroll=!1)}var d=this;document.attachEvent?(this.ta.attachEvent("onmousewheel",function(a){a=a||window.event;d._scroll(a)}),this.sb.attachEvent("onmousewheel",function(a){a=a||window.event;d._scroll(a)})):(this.ta.addEventListener("mousewheel",function(a){a=a||window.event;
d._scroll(a)},!1),this.ta.addEventListener("DOMMouseScroll",function(a){a=a||window.event;d._scroll(a)},!1),this.sb.addEventListener("mousewheel",function(a){a=a||window.event;d._scroll(a)},!1),this.sb.addEventListener("DOMMouseScroll",function(a){a=a||window.event;d._scroll(a)},!1));attachEvnt(this.ta,"touchstart",function(e){e=e||window.event;d.mousePos={x:e.touches[0].clientX,y:e.touches[0].clientY};attachEvnt(document,"touchmove",a);attachEvnt(document,"touchend",c)});this.st.onmousedown=function(a){d.mousePos=
getMousePos(a);document.onmouseup=function(a){document.onmousemove=null;document.onmouseup=null;!1==d.onSb&&(d.isScroll=!1)};document.onmousemove=function(a){var b=getMousePos(a),c=b.y-d.mousePos.y,c=parseFloat(d.st.style.top)+c,c=c>=d.sbcH?d.sbcH:0>=c?0:c;d.st.style.top=c+"px";d.mousePos.y=b.y;d.ta.scrollTop=d.scH*(c/d.sbcH);d.isScroll=!0;clearSelection(a)}};selector("#"+this.sb.id)[0].onmouseover=function(a){a=a||window.event;d.onSb=!0;!0==d.show&&d._scrollShow(a)};selector("#"+this.sb.id)[0].onmouseout=
function(){d.onSb=!1;d.isScroll=!1}},NiceScroll.prototype._close=function(){this.sb.style.visibility="hidden";this.enabled=!1},NiceScroll.prototype._open=function(){this.enabled=!0},NiceScroll.prototype._shSb=function(){this.sb.style.visibility="none"==this.ta.style.display||"hidden"==this.ta.visibility?"hidden":"visible"},NiceScroll.prototype._check=function(){null==id(this.taId)?(window.clearTimeout(this.checkTt),this.sb.parentNode.removeChild(this.sb)):!1!=this.enabled&&(!1==checkInHorize(this.ta)?
this.sb.style.display="none":(this.sb.style.display="block",0>=parseInt(this.ta.offsetHeight)&&(this.sb.style.visibility="hidden"),this._reset()))},NiceScroll.prototype._getWheelDelta=function(a){a=a||window.event;return a.wheelDelta?window.opera&&9.5>window.opera.version?-a.wheelDelta:a.wheelDelta:40*-a.detail},NiceScroll.prototype._wheelAnimate=function(a,c){var d=this,e=!1;this.wtId?(this.wtCounter=(e=0>(this.woSpeed^a))?c:50>this.wtCounter+c?this.wtCounter+c:50,this.wSpeed=e?a:1.05*this.wSpeed):
(this.wtCounter=c,this.woSpeed=this.wSpeed=a,function(){var a=0;d.wtId=window.setTimeout(arguments.callee,5);if(0>d.wtCounter)clearTimeout(d.wtId),d.wtId=null,!1==d.onSb&&(d.isScroll=!1);else{a=parseFloat(d.ta.scrollTop)+parseInt(d.wSpeed);if(a>=d.scH||0>=a)d.wtCounter=0;d.ta.scrollTop=a;a=d.ta.scrollTop/d.scH*d.sbcH;isNaN(a)||(d.st.style.top=a+"px");d.wtCounter--}}())},NiceScroll.prototype._scrollShow=function(a){this.isScroll=!0;eventPreventDefault(a)},NiceScroll.prototype._scroll=function(a){a=
a||window.event;var c=0<this._getWheelDelta(a)?-1:1;!0==this.show&&!0==this.enabled&&(this._scrollShow(a),this._wheelAnimate(5*c,7))})}
function DateControl(a,b){this.table;this.weekList;this.hourList;this.dateCon=id(a);this.weekIsMouseDown=!1;this.selDate=[0,0,0,0,0,0,0];this.dateArray=[0,0,0,0,0,0,0];this.cellWidth=this.cellHeight=22;this.cellSeColor="#A0D468";this.cellDeColor="#FAFAFA";this.cellPadding=1;void 0==DateControl.prototype.init&&(DateControl.prototype.hourStr=label.hour,DateControl.prototype.weekDayNum=7,DateControl.prototype.lineStr="-",DateControl.prototype.selTag="selTag",DateControl.prototype.cellBorderWidth=1,DateControl.prototype.iCellIndex=
0,DateControl.prototype.weekArray=[label.Mon,label.Tue,label.Wen,label.Thu,label.Fri,label.Sta,label.Sun],DateControl.prototype._init=function(){this._initOptions();this._dateConInit();this._hourListInit();this._weekListInit();this._dateTableInit()},DateControl.prototype.reset=function(a){var b,e,f,g=this.iCellIndex;if(!1!=a instanceof Array&&void 0!=a&&a.length==this.weekDayNum)for(var h=0;h<this.weekDayNum;h++){e=this.table.rows[h];b=a[h];for(var k=0;24>k;k++)f=e.cells[k],f=f.childNodes[g],void 0!=
b?(this._setSel(f,b%2),b>>=1):this._setSel(f,0)}},DateControl.prototype._initOptions=function(){for(var a in b)"undefined"!=typeof this[a]&&(this[a]=b[a])},DateControl.prototype.getSelDate=function(){var a,b,e=this.weekDayNum,f=this.table.rows;this.selDate=[0,0,0,0,0,0,0];for(var g=0;g<e;g++){b=f[g];for(var h=0;24>h;h++)a=b.cells[h],a=a.childNodes[0],a=parseInt(a.getAttribute("sel")),1==a&&(this.selDate[g]+=Math.pow(2,h))}return this.selDate},DateControl.prototype._dateConInit=function(){this.dateCon.style.overflow=
"hidden"},DateControl.prototype._hourListInit=function(){var a=document.createElement("ul"),b,e,f=this;a.className="hourList";for(var g=0;24>=g;g++)b=document.createElement("li"),24!=g?(e=document.createElement("i"),e.innerHTML=g,b.appendChild(e),b.style.width=this.cellWidth+2*this.cellPadding+this.cellBorderWidth+"px",e.onclick=function(a){return function(){for(var b=f.table.rows,c=b.length,d=f.iCellIndex,e=1,g=0;g<c&&(e&=parseInt(b[g].cells[a].childNodes[d].getAttribute("sel")),0!=e);g++);e=1-e;
for(g=0;g<c;g++)f._setSel(b[g].cells[a].childNodes[d],e);clearSelection()}}(g)):b.innerHTML="<i>"+this.hourStr+"</i>",a.appendChild(b);this.dateCon.appendChild(a);this.hourList=a},DateControl.prototype._weekListInit=function(){var a=document.createElement("ul"),b,e=this;a.className="weekList";for(var f=0,g=this.weekDayNum;f<g;f++)b=document.createElement("li"),b.style.height=this.cellHeight+2*this.cellPadding+this.cellBorderWidth+"px",b.style.lineHeight=this.cellHeight+2*this.cellPadding+this.cellBorderWidth+
"px",b.innerHTML=this.weekArray[f],b.onclick=function(a){return function(){for(var b=e.table.rows[a].cells,c=e.iCellIndex,d=1,f=0,g=b.length;f<g&&(d&=parseInt(b[f].childNodes[c].getAttribute("sel")),0!=d);f++);d=1-d;f=0;for(g=b.length;f<g;f++)e._setSel(b[f].childNodes[c],d);clearSelection()}}(f),a.appendChild(b);this.dateCon.appendChild(a);this.weekList=a},DateControl.prototype._setSel=function(a,b){a.setAttribute("sel",b);a.style.backgroundColor=1==b?this.cellSeColor:this.cellDeColor},DateControl.prototype._dateCellCreate=
function(){for(var a,b,e,f,g=this,h=0,k=this.weekDayNum;h<k;h++){b=this.table.insertRow(-1);void 0!=this.dateArray&&(a=this.dateArray[h]);for(var l=0;24>l;l++)e=b.insertCell(-1),e.style.padding=this.cellPadding+"px",e.className="weekTd",f=document.createElement("i"),f.className="tableICell",f.style.height=this.cellHeight+"px",f.style.width=this.cellWidth+"px",e.appendChild(f),this._setSel(f,0),void 0!=a?(this._setSel(f,a%2),a>>=1):this._setSel(f,0),f.onmouseover=function(a){!0==g.weekIsMouseDown&&
g._setSel(this,1-parseInt(this.getAttribute("sel")))},f.onmousedown=function(a){g._setSel(this,1-parseInt(this.getAttribute("sel")))}}3==this.table.rows[0].cells[0].nodeType&&(this.iCellIndex=1)},DateControl.prototype._dateCellBind=function(){var a=this;this.table.onmousedown=function(b){a.weekIsMouseDown=!0;document.onmouseup=function(b){a.weekIsMouseDown=!1}};this.table.onmouseup=function(b){a.weekIsMouseDown=!1}},DateControl.prototype._dateTableCreate=function(){this.table=document.createElement("table");
this.table.className="tableWeek";this.table.cellspacing="0px";this.table.cellpadding="0px";this.dateCon.appendChild(this.table)},DateControl.prototype._dateTableInit=function(){this._dateTableCreate();this._dateCellCreate();this._dateCellBind()});this._init()}
function PageFunc(){this.pathStr="../";this.htmlPathStr=this.pathStr+"common/";this.detectPathStr="/images/logo_me.png";this.loginId="Login";this.loadPageData={url:"",id:""};this.isPostfunc;this.helpIdStr="helpStr";this.LGKEYSTR="lgKey";this.LGKEYTIMESTR="lgKeyTime";this.domainUrl="mwlogin.net";this.g_homePageUpdate=this.showPortablePage=!0;this.gGetWdsScanResultDelay=1E3;this.$Init=function(){Quary.call(jQuery);$.setDataParseFunc($.parser);$.getExplorer();$.initUrl()};this.logout=function(){$.logout();
loadPage("Content.htm","Con");id("Con").innerHTML=""};this.loadPageHandleBg=function(){var a=selector("i.helpBtn"),b;initHoverBd();for(var c=0,d=a.length;c<d;c++)b=a[c],b=b.getAttribute(helpIdStr),null!=b&&helpBind(a[c],b)};this.loadPage=function(a,b,c){var d=this;window.setTimeout(function(){helpClose();closeAlert();closeConfirm();$.load(d.htmlPathStr+a,function(){try{"function"==typeof pageOnloadMenuCallback&&pageOnloadMenuCallback()}catch(a){}"function"==typeof c&&c()},b)},0)};this.pageRedirect=
function(){var a=window.top.location.href;USER_GROUP_REMOTE!=$.group&&!1==/^((http:\/\/)*(\d{1,3}\.){3}\d{1,3})/g.test(a)&&0>a.indexOf(domainUrl)&&!1==$.local&&(window.top.location.href=$.httpTag+domainUrl)};this.pageOnloadInit=function(){try{showPortablePage=!0==gotopc||!1==OS.portable?!1:!0}catch(a){}!0==showPortablePage?selector("meta[name=viewport]")[0].setAttribute("content","width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"):selector("meta[name=viewport]")[0].setAttribute("content",
"width=1000, initial-scale=1.0, minimum-scale=0.5, maximum-scale=2.0, user-scalable=yes")};this.pageOnloadDispense=function(){var a=window.top.location.href;!1==/^((http:\/\/)*(\d{1,3}\.){3}\d{1,3})/g.test(a)&&0<=a.indexOf(domainUrl)?$.getDevDiscover(function(a){ENONE==a.errorno?(a=$.findBlock(DEV_DISCOVER_LIST_DATA_ID),1<a.count?!1==showPortablePage?loadPage("RouterSelect.htm","Con"):loadPage("PhoneRouterSelect.htm","Con"):loadPage("Content.htm","Con")):loadPage("Content.htm","Con")}):loadPage("Content.htm",
"Con")};this.pageOnload=function(){var a=[{tag:"link",url:"../dynaform/menu.css"},{tag:"link",url:"../dynaform/DataGrid.css"}],b=[{tag:"script",url:"../lib/verify.js"},{tag:"script",url:"../dynaform/macFactory.js"},{tag:"script",url:"../dynaform/DataGrid.js"},{tag:"script",url:"../dynaform/menu.js"}];this.loadExternResource({scripts:[{tag:"script",url:"../lib/model.js"},{tag:"script",url:"../lib/DM.js"},{tag:"script",url:"../language/eu/str.js"},{tag:"script",url:"../language/eu/error.js"},{tag:"script",
url:"../lib/Quary.js"},{tag:"script",url:"../lib/ajax.js"}],callBack:function(){$Init();$.setexternJSP(replaceJSP);$.setExternPageHandle(loadPageHandleBg);$.setLoginErrHandle(showLogin);$.setPRHandle(pageRedirect);window.authInfo=[];this.loadExternResource({scripts:b,links:a});this.compatibleShow();this.localSgInit();this.pageOnloadInit();this.pageOnloadDispense()}});document.oncontextmenu=function(a){return!1};if(isIESix)try{document.execCommand("BackgroundImageCache",!1,!0)}catch(c){}};this.unloadDetail=
function(a){if(a=id(a))a.innerHTML=""};this.detailShow=function(a,b){};this.detailHide=function(a,b){};this.selectChange=function(a,b){id(a).value=b.options[b.selectedIndex].text};this.loginChange=function(a){var b=this.id(this.loginId),c="block",d="none",e,f=document.body.childNodes;!0==a&&(c="none",d="block");for(var g in f)e=f[g],void 0!=e.nodeName&&"DIV"==e.nodeName.toUpperCase()&&e.id!=this.loginId&&this.setStyle(e,{display:c});b.innerHTML="";this.setStyle(b,{display:d});!0==a?$.unChgPwd==authInfo[1]?
(id("Con").innerHTML="",!0==OS.portable&&!1==OS.iPad?this.loadPage("PhoneLoginChgPwd.htm",this.loginId):this.loadPage("LoginChgPwd.htm",this.loginId)):($.setLgPwd(""),!1==gotopc&&!0==OS.portable&&!1==OS.iPad?this.loadPage("PhoneLogin.htm",this.loginId):this.loadPage("Login.htm",this.loginId)):$.unChgPwd==authInfo[1]?loadPage("Content.htm","Con"):this.isPostfunc?this.isPostfunc():this.loadPage(this.loadPageData.url,this.loadPageData.id)};this.setLoadPage=function(a,b){this.loadPageData.url=a;this.loadPageData.id=
b};this.localSgInit=function(){try{this.sessionLS.init(),!0==isIE&&!1==isIENormal&&function(){sessionLS.setExpire(3E3);window.setTimeout(arguments.callee,1E3)}()}catch(a){}this.getLgPwd()};this.auth=function(){$.auth($.pwd)};this.getLgPwd=function(){try{$.pwd=sessionLS.getItem(this.LGKEYSTR)}catch(a){}};this.showLogin=function(a){this.isPostfunc=a;this.loginChange(!0)};this.unloadLogin=function(){this.loginChange(!1)};this.iFrmOnload=function(a,b,c){var d;c=ENONE;a=id(a);var e=!1;try{d=a.contentWindow?
a.contentWindow.document.body?a.contentWindow.document.body.innerHTML:null:a.contentDocument.document.body?a.contentDocument.document.body.innerHTML:null,e=/([0-9]+)/g.test(d),c=!1==e?EINVFMT:parseInt(RegExp.$1),c!=ENONE&&closeProgressNum(),b(c)}catch(f){closeProgressNum(),b(EINVFMT)}};this.windowSleep=function(a){var b=new Date;for(a=b.getTime()+a;!(b=new Date,b.getTime()>a););};this.getCurrPcMac=function(){var a,b=$.getPeerMac();if(ENONE!=b.errorno||""==b.data)return"00-00-00-00-00-00";a=b.data.indexOf("\r\n");
return b.data.substring(0,a)};this.cloneLocalMac=function(){var a=$.readEx(SYSTEM_DATA_ID),b=this.getCurrPcMac(),c=ENONE;a.mac[1]!=b&&(a.mac[1]=b,c=$.write($.toText(a),$.block));return c};this.logSave=function(){location.href=$.orgURL($.domainUrl+"syslog.txt?code="+TDDP_INSTRUCT+"&asyn=0&disposition=1");return!0};this.loadExternResource=function(a){var b,c,d,e,f=document.getElementsByTagName("head")[0];b={links:null,scripts:null,callBack:null};for(var g in a)b[g]=a[g];a=b.links;c=b.scripts;d=b.callBack;
if(void 0!=a)for(var h in a)b=document.createElement("link"),b.rel="stylesheet",b.href=a[h].url,f.appendChild(b);if(void 0!=c){var k;b=document.createElement("script");b.type="text/javascript";if(void 0!=d)for(h in e=void 0!=b.readyState,k=function(a){c[a].loadState=!0;for(var b in c)if(!1==c[b].loadState)return;d()},c)c[h].loadState=!1;for(h in c)b=document.createElement("script"),b.type="text/javascript",void 0!=d&&(e?b.onreadystatechange=function(a){return function(){if("loaded"==this.readyState||
"complete"==this.readyState)this.onreadystatechange=null,k(a)}}(h):b.onload=function(a){return function(){k(a)}}(h)),b.src=c[h].url,f.appendChild(b)}}}
function Cover(){Style.call(this);this.CoverId="Cover";this.hideCover=function(a,b){var c=id(this.CoverId);this.setStyle(c,{display:"none",visibility:"hidden"});this.setStyle(c,b);"undefined"!=typeof a&&a(c);c.innerHTML=""};this.showCover=function(a,b){var c=id(this.CoverId);this.setStyle(c,{display:"block",visibility:"visible"});this.setStyle(c,b);"undefined"!=typeof a&&a(c)}}
function Style(){this.disableCol="#b2b2b2";this.setStyle=function(a,b){if(null!=a&&null!=b&&1==a.nodeType)for(var c in b)try{a.style[c]=b[c]}catch(d){}};this.getNodeDefaultView=function(a,b){var c=null;if(!a)return null;try{return c=a.currentStyle?a.currentStyle:document.defaultView.getComputedStyle(a,null),void 0!=b?c[b]:c}catch(d){}}}
function LocalStorageSD(){try{this.sessionLS=null==this.sessionStorage?{file_name:"user_data_default_SD",dom:null,init:function(){var a=document.createElement("input");a.type="hidden";a.addBehavior("#default#userData");document.body.appendChild(a);a.save(this.file_name);this.dom=a},setItem:function(a,c){this.dom.setAttribute(a,c);this.dom.save(this.file_name)},getItem:function(a,c){this.dom.load(this.file_name);return this.dom.getAttribute(a)},removeItem:function(a){this.dom.removeAttribute(a);this.dom.save(this.file_name)},
setExpire:function(a){var c=new Date,c=new Date(c.getTime()+a);this.dom.load(this.file_name);this.dom.expires=c.toUTCString();this.dom.save(this.file_name)}}:sessionStorage}catch(a){}}
function Explorer(){this.isIESixorSeven=this.isIETenLess=this.isIENormal=this.isIESeven=this.isIESix=this.isIE=!1;this.explorerInfo=navigator.userAgent;this.getIEInfo=function(){isIE=/msie ((\d+\.)+\d+)/i.test(explorerInfo)?document.mode||RegExp.$1:!1;if(6==isIE||7==isIE)isIESixorSeven=!0;!1!=isIE&&(6>=isIE?this.isIESix=!0:7==isIE?this.isIESeven=!0:9<=isIE&&(this.isIENormal=!0),10>=isIE&&(this.isIETenLess=!0),this.isIE=!0)};this.compatibleShow=function(){if(!0==this.isIESix){var a,b,c,d,e;0<=document.cookie.indexOf("ieSixClosed")||
(a=selector("div.ieSixCompatible"),void 0==a[0]&&(a=el("div"),a.className="ieSixCompatible",b=el("div"),b.className="ieSixCpCon",c=el("i"),d=el("span"),d.className="spanNote",d.innerHTML=label.IESixCpTip,e=el("span"),e.className="spanClose",e.innerHTML=label.iknown,e.onclick=function(){document.cookie="ieSixClosed=true";a.style.visibility="hidden";a.style.top="-9999px"},b.appendChild(c),b.appendChild(d),b.appendChild(e),a.appendChild(b),document.body.appendChild(a)))}};this.createGroupRadio=function(a){var b;
if(void 0==a)return b;!0==this.isIE&&!1==this.isIENormal?b=document.createElement("<input name='"+a+"' />"):(b=document.createElement("input"),b.name=a);return b};this.getIEInfo()}
function Tool(){Style.call(this);this.addBtnClickStyle=function(a){id(a).onmousedown=function(b){selector("#"+a).style.background="#1E4444"};id(a).onmouseup=function(b){selector("#"+a).style.background="#ff6060"};id(a).onmouseout=function(b){selector("#"+a).style.background="#ff6060"}};this.addBtnClickStyle2=function(a){id(a).onmousedown=function(b){selector("#"+a).style.background="#1E4444"};id(a).onmouseup=function(b){selector("#"+a).style.background="#e9e2e2"};id(a).onmouseout=function(b){selector("#"+
a).style.background="#e9e2e2"}};this.id=function(a){if(void 0!=a)return document.getElementById(a)};this.selector=function(a){if("string"!=typeof a||0==a.length)return null;a=a.replace(/\s+/g," ");a=a.replace(/^\s+|\s+$/g,"");return isIESixorSeven?ieLowSelector(a):document.querySelectorAll(a)};this.setCss=function(a,b,c){if(!a)return null;if(void 0!=a.length)for(i=0;i<a.length;i++)a[i].style[b]=c;else a.style[b]=c};this.getCss=function(a,b){var c;return a?a.currentStyle?(c=a.currentStyle[b],"width"!==
b&&"height"!==b||"auto"!==c||(c=a.getBoundingClientRect(),c="width"===b?c.right-c.left:c.bottom-c.top),c):window.getComputedStyle(a,null)[b]:null};this.setAttr=function(a,b,c){if(!a)return null;if(void 0!=a.length)for(i=0;i<a.length;i++)a[i].setAttribute(b,c);else a.setAttribute(b,c)};this.hasClass=function(a,b){return a.className.match(RegExp("(\\s|^)"+b+"(\\s|$)"))};this.addClass=function(a,b){this.hasClass(a,b)||(a.className+=a.className?" "+b:b)};this.removeClass=function(a,b){this.hasClass(a,
b)&&(a.className=a.className.replace(RegExp("(\\s|^)"+b+"(\\s|$)")," "))};this.toggleClass=function(a,b){var c,d,e,f,g;if(null===b)return null;c=b.split(" ");if(void 0!=a.length)for(f=0,e=c.length;f<e;f++)for(g=0,d=a.length;g<d;g++)this.hasClass(a[g],c[f])?this.removeClass(a[g],c[f]):this.addClass(a[g],c[f]);else if(a)for(f=0,e=c.length;f<e;f++)this.hasClass(a,c[f])?this.removeClass(a,c[f]):this.addClass(a,c[f]);else return null};this.getTarget=function(a){return(a||window.event).target||a.srcElement};
this.eventAdd=function(a,b,c){if(!a)return null;if(void 0!=a.length)for(var d=0;d<a.length;d++)this.attachEvnt(a[d],b,c);else this.attachEvnt(a,b,c)};this.eventRmv=function(a,b,c){if(!a)return null;if(void 0!=a.length)for(var d=0;d<a.length;d++)this.detachEvnt(a[d],b,c);else this.detachEvnt(a,b,c)};this.eventOnce=function(a,b,c){if(!a)return null;if(void 0!=a.length)for(var d=0;d<a.length;d++)this.onceEvnt(a[d],b,c);else this.onceEvnt(a,b,c)};this.el=function(a){try{return document.createElement(a)}catch(b){return null}};
this.removeEl=function(a){if(!a)return null;if(void 0!=a.length)for(var b=0;b<a.length;b++)a[b].parentNode.removeChild(a[b]);else a.parentNode.removeChild(a)};this.ieLowSelector=function(a){var b=document.getElementsByTagName("*"),c=[],d=a.indexOf(","),e=a.indexOf(" ");if(0<d)for(a=a.split(","),e=0;e<a.length;e++)d=ieLowSelectorFind(a[e],b),0==d.length?null:c.push.apply(c,d);else if(0<e){a=a.split(" ");for(e=0;e<a.length;e++){if(!b)return[];b=ieLowSelectorFind(a[e],b)}c=b}else if(a)c=ieLowSelectorFind(a,
b);else return null;return c};this.ieLowSelectorFind=function(a,b){var c=[],d=b;if(!d)return[];if(a.match(/^#[a-zA-Z]{1}[a-zA-Z0-9-_.:]*$/))document.getElementById(a.split("#")[1])&&c.push(document.getElementById(a.split("#")[1]));else if(1<a.split(".").length){var c=[],e=a.split(".")[0];for(i=1;i<a.split(".").length;i++)c.push(a.split(".")[i]);if(""!=e&&(d=getTagEl(d,e),!d))return[];c=getClassEl(d,c)}else{var f,g;if(a.match(/^[a-zA-Z_-]+\[[a-zA-Z0-9-_.:=]*\]$/)){e=a.split("[")[0];f=a.split("[")[1].match(/[a-zA-Z0-9-_.:=]*/)[0];
if(2==f.split("=").length)g=f.split("=")[0],f=f.split("=")[1];else return null;d=getTagEl(d,e);for(i=0;i<d.length;i++)d[i].getAttribute(g)==f?c.push(d[i]):null}else c=getTagEl(d,a)}return c};this.getTagEl=function(a,b){var c,d,e=[];c=a instanceof Array?a:HTMLCollection2Array(a);for(i=0;i<c.length;i++)for(d=c[i].getElementsByTagName(b),j=0;j<d.length;j++)checkArrSame(d[j],e)||e.push(d[j]);return e};this.checkArrSame=function(a,b){if(0<b.length)for(var c=0;c<b.length;c++)if(a===b[c])return!0;return!1};
this.getClassEl=function(a,b){var c,d=[];c=a instanceof Array?a:HTMLCollection2Array(a);for(i=0;i<c.length;i++)if(isIESix&&hasClass(c[i],b[b.length-1]))d.push(c[i]);else for(j=0,csaLength=b.length;j<csaLength&&hasClass(c[i],b[j]);j++)d.push(c[i]);return d};this.HTMLCollection2Array=function(a){for(var b=[],c=0;c<a.length;c++)b.push(a[c]);return b};this.replaceJSP=function(a){var b=null,c,d=/<%(\w+)\.(\w+)%>/i,b=d.exec(a);try{for(;null!=b;)c=language[b[1]][b[2]],a=a.replace("<%"+b[1]+"."+b[2]+"%>",
c),b=d.exec(a)}catch(e){}return a};this.getoffset=function(a){for(var b={top:0,left:0};;){b.left+=parseInt(a.offsetLeft);b.top+=parseInt(a.offsetTop);try{a=a.offsetParent}catch(c){a=null}if(null==a||"BODY"==a.tagName.toUpperCase()||"HTML"==a.tagName.toUpperCase())break}return b};this.attachEvnt=function(a,b,c){0==b.indexOf("on")&&(b=b.substring(2));document.body.attachEvent?a.attachEvent("on"+b,c):a.addEventListener(b,c)};this.detachEvnt=function(a,b,c){0==b.indexOf("on")&&(b=b.substring(2));document.body.attachEvent?
a.detachEvent("on"+b,c):a.removeEventListener(b,c,!1)};this.onceEvnt=function(a,b,c){var d;0==b.indexOf("on")&&(b=b.substring(2));document.body.attachEvent?(d=function(){c();a.detachEvent("on"+b,d)},a.attachEvent("on"+b,d)):(d=function(){c();a.removeEventListener(b,d,!1)},a.addEventListener(b,d,!1))};this.stopProp=function(a){a=a||window.event;a.stopPropagation?a.stopPropagation():a.cancelBubble=!0};this.eventPreventDefault=function(a){a=a||window.event;a.preventDefault?a.preventDefault():a.returnValue=
!1};this.clearSelection=function(){window.getSelection?window.getSelection().removeAllRanges():document.selection.empty()};this.setDomCursorPos=function(a,b){if(a.setSelectionRange)a.focus(),a.setSelectionRange(b,b);else if(a.createTextRange){var c=a.createTextRange();c.collapse(!0);c.moveEnd("character",b);c.moveStart("character",b);c.select()}};this.getMousePos=function(a){a=a||window.event;var b=document;return a.pageX||a.pageY?{x:a.pageX,y:a.pageY}:{x:a.clientX+b.documentElement.scrollLeft-b.documentElement.clientLeft,
y:a.clientY+b.documentElement.scrollTop-b.documentElement.clientTop}};this.isArray=function(a){return"[object Array]"===Object.prototype.toString.call(a)};this.getChildNode=function(a,b,c){a=a.childNodes;var d=[],e=0,f;f=b.split(" ");b=f[0];for(var g=f[1],h=0,k=a.length;h<k;h++)f=a[h],f.tagName.toLowerCase()==b&&(void 0!=g&&f.type==g?(d[e]=f,e++):void 0==g&&(d[e]=f,e++));return void 0!=c?d[c]:d[0]};this.checkInHorize=function(a){for(;null!=a&&"HTML"!=a.nodeName.toUpperCase();){if("hidden"==this.getNodeDefaultView(a,
"visibility")||"none"==this.getNodeDefaultView(a,"display"))return!1;a=a.parentNode}return!0};this.setUrlHash=function(a,b){var c,d,e;c="";var f=location.href;d=location.hash;void 0!=a&&void 0!=b&&0!=a.length&&(0!=d.length?(e=d.indexOf(a),0<=e?(c=d.substring(0,e),d=d.substring(e),e=d.indexOf("#"),0<e?(d=d.substring(e),d=c+a+"="+b+d):d=c+a+"="+b):("#"!=d.substring(d.length-1)&&(c="#"),d+=c+a+"="+b),location.href=f.substring(0,f.indexOf("#"))+d):f.lastIndexOf("#")==f.length-1?location.href+=a+"="+b:
location.href+="#"+a+"="+b)};this.getUrlHash=function(a){var b=location.hash,c,d="";if(0<b.indexOf(a)){var b=b.substring(1).split("#"),e;for(e in b)if(c=b[e].split("="),c[0]==a){d=c[1];break}}return d};this.changeUrlHash=function(a){var b=location.href,c=b.indexOf("#");void 0!=a&&(location.href=0<c?b.substring(0,c+1)+a:b+"#"+a)};this.setInputCursor=function(a){this.setDomCursorPos(a,a.value.length)};this.getCNStrLen=function(a){return a.replace(/[^\x00-\xFF]/g,"xxx").length};this.getCNStrHTMLLen=
function(a){return a.replace(/[^\x00-\xFF]/g,"xx").length};this.getStrInMax=function(a,b){var c="",d,e=0;d=a.replace(/[A-Z]/g,"xx");if(getCNStrHTMLLen(d)<=b)return a;for(var f=1;f<=b;f++){d=a.charAt(e);if(""==d)break;2==getCNStrHTMLLen(d)||!0==/[A-Z]/g.test(d)?(f++,c+=d,beCut=!0):c+=d;e++}return c+"..."};this.encodeBlankspace=function(a){return a.replace(/ /g,"%20")};this.EncodeURLIMG=document.createElement("img");this.escapeDBC=function(a){var b=this.EncodeURLIMG;if(!a)return"";if(window.ActiveXObject)return execScript('SetLocale "zh-cn"',
"vbscript"),a.replace(/[\d\D]/g,function(a){window.vbsval="";execScript('window.vbsval=Hex(Asc("'+a+'"))',"vbscript");return"%"+window.vbsval.slice(0,2)+"%"+window.vbsval.slice(-2)});b.src="nothing.png?separator="+a;return b.src.split("?separator=").pop()};this.encodeURL=function(a){return encodeURIComponent(a)};this.doNothing=function(){return!0};this.htmlEscape=function(a){void 0!=a&&(a=a.toString().replace(/[<>&"]/g,function(a){switch(a){case "<":return"&lt;";case ">":return"&gt;";case "&":return"&amp;";
case '"':return"&quot;"}}));return a};this.simulateMouseC=function(a){simulateMouseC=!0==isIE&&!1==isIENormal?function(a){var c=document.createEventObject();c.sceenX=100;c.sceenY=0;c.clientX=0;c.clientY=0;c.ctrlKey=!1;c.altKey=!1;c.shiftKey=!1;c.button=0;a.fireEvent("onclick",c)}:function(){var b=document.createEvent("MouseEvents");b.initMouseEvent("click",!0,!0,document.defaultView,0,0,0,0,0,!1,!1,!1,!1,0,null);a.dispatchEvent(b)};simulateMouseC(a)};this.autoFitBodyFont=function(){var a=12*window.innerWidth/
320;document.body.style.fontSize=(12>a?12:a)+"px"};this.solveInputTextCover=function(a){void 0==a&&(a="phoneContent");eventAdd(selector("input[type=text],input[type=password]"),"focus",function(){setCss(selector("div."+a),"padding-bottom","40%")});eventAdd(selector("input[type=text],input[type=password]"),"blur",function(){setCss(selector("div."+a),"padding-bottom","0")})}}
function Switch(a,b,c){this.switchCon=id(a);this.switchBall=selector("#"+a+" i.switchBall")[0];this.switchBg=selector("#"+a+" i.switchBg")[0];this.callback=c;this.state=b;this.rightPos;"function"!=typeof Switch.prototype.switchInit&&(Switch.prototype.switchInit=function(){var a=this.state,b=this.switchBall,c=this.switchCon,g=this.switchBg;null!=c&&null!=b&&(this.rightPos=c.offsetWidth-b.offsetWidth,this.setState(a),this.callback&&this.callback(a),b.onmousedown=this.draggableBind(),g.onclick=this.switchBgClick())},
Switch.prototype.setState=function(a){var b=this.switchCon,c=this.switchBall,g=this.switchBg;this.state=a;b.value=a;c.style.left=(1-a)*this.rightPos+(1==a?2:-2)+"px";g.style.background=1==a?"url(../images/basic_me.png) no-repeat scroll -151px -299px":"url(../images/basic_me.png) no-repeat scroll -102px -299px"},Switch.prototype.switchChgState=function(a){a=1-a;this.setState(a);this.callback&&this.callback(a)},Switch.prototype.switchCHandle=function(){var a=this.state,b=this.switchBall,c=1==a?1:-1,
g=parseInt(b.style.left),h=this.rightPos-2,k=this;0==a&&2>=g||1==a&&g>=h?this.switchChgState(a):(b.style.left=g+c*h/8+"px",window.setTimeout(function(){k.switchCHandle()},20))},Switch.prototype.msMove=function(a,b,c){b=b.x-c.x;c=this.switchCon.offsetWidth-a.offsetWidth-2;b=2<b?b:2;a.style.left=(b>c?c:b)+"px"},Switch.prototype.switchBgClick=function(){var a=this;return function(b){b=b||window.event;a.switchBg==(b.target||b.srcElement)&&a.switchCHandle()}},Switch.prototype.draggableBind=function(){var a=
this;return function(b){b=b?b:window.event;var c=getMousePos(b),g=b.target||b.srcElement,h={x:c.x-g.offsetLeft};document.onmousemove=function(b){b=b?b:window.event;b=getMousePos(b);clearSelection();a.msMove(g,b,h)};document.onmouseup=function(b){clearSelection();document.onmousemove=null;document.onmouseup=null;a.switchCHandle()};stopProp(b)}});this.switchInit()}
function HighSet(){this.hsLoadingObj={subBtnId:"",isBasic:!1,isWl:!1,handleCor:"",handleLoad:"",subLoadingHeight:""};this.hsStatSet=function(a,b,c){var d,e;void 0==c?(d=selector("div.handleRelCon")[0],e=selector("div.handleRelCon i.state")[0],c=selector("div.handleRelCon span.state")[0]):(d=selector("#"+c)[0],e=selector("#"+c+" i.state")[0],c=selector("#"+c+" span.state")[0]);switch(a){case "null":d.style.visibility="hidden";break;case "correct":e.style.background="url(../images/wzd_me.png) no-repeat -282px -128px";
c.style.color="#808080";c.innerHTML=b;d.style.visibility="visible";break;case "error":e.style.background="url(../images/wzd_me.png) no-repeat -282px -108px";c.style.color="#FF6060";c.innerHTML=b;d.style.visibility="visible";break;case "link":e.style.background="url(../images/wzd_me.png) no-repeat -282px -169px",c.style.color="#FFC600",c.innerHTML=b,d.style.visibility="visible"}};this.disInputTip=function(a,b){null!=a&&void 0!=b&&("error"==b.toLowerCase()?this.setStyle(a,{visibility:"visible",background:"url(../images/wzd_me.png) no-repeat -282px -108px"}):
"ok"==b.toLowerCase()?this.setStyle(a,{visibility:"visible",background:"url(../images/wzd_me.png) no-repeat -282px -128px"}):"warn"==b.toLowerCase()?this.setStyle(a,{visibility:"visible",background:"url(../images/wzd_me.png) no-repeat -282px -148px"}):a.style.visibility="hidden")};this.initHoverBd=function(){eventAdd(selector("input.hoverBd"),"focus",function(a){getTarget(a).parentNode.style.border="1px solid #009900"});eventAdd(selector("input.hoverBd"),"blur",function(a){getTarget(a).parentNode.style.border=
"1px solid #666666"})};this.disableInput=function(a,b){var c="object"==typeof a?a:id(a);c.disabled=b?!0:!1;c.style.color=b?"#B2B2B2":"#000000";c.style.backgroundColor="#FFFFFF"};this.disableBtn=function(a,b,c,d,e){a="object"==typeof a?a:id(a);for(var f=a.className.split(" "),g=0,h=f.length;g<h;g++)if(f[g]==c)f[g]=d;else if(f[g]==d)return;a.className=f.join(" ");a.onclick=b?null:e};this.setLoadingId=function(a,b,c){this.hsLoadingObj.subBtnId=a;this.hsLoadingObj.isBasic=void 0!=b;this.hsLoadingObj.isWl=
void 0!=c};this.hsLoading=function(a){var b=this.hsLoadingObj,c=id(b.subBtnId),d,e,f,g,h,k,l=this;null!=c&&(h=c.parentNode,h.style.position="relative",c.className=c.className,d=c.offsetLeft,f=c.offsetTop,g=c.offsetWidth,e=c.offsetHeight,k=selector("i[name=hsSubLoading]")[0],void 0==k&&(k=el("i"),k.className="hsSubLoading",setAttr(k,"name","hsSubLoading"),h.appendChild(k),b.subLoadingHeight=parseInt(getNodeDefaultView(k,"height"))),a?(window.clearTimeout(b.handleLoad),window.clearTimeout(b.handleCor),
"none"!=k.style.display&&(k.style.display="none"),2<=c.childNodes.length&&(a=selector("#"+b.subBtnId+" i")[0],g=a.offsetWidth,e=a.offsetHeight),k.style.background="url(../images/wanDetecting_me.gif)",k.style.left=d+g+5+"px",k.style.display="inline-block",k.style.top=f+(e-b.subLoadingHeight)/2+"px"):(l.hsLoadingObj.subBtnId="",ENONE!=$.result.errorno?void 0!=k&&(k.style.display="none"):b.handleLoad=$.setTimeout(function(){void 0!=k&&(k.style.background="url(../images/wzd_me.png) no-repeat -282px -128px",
l.hsLoadingObj.handleCor=$.setTimeout(function(){void 0!=k&&(k.style.display="none")},2E3))},1E3)))}}function Basic(){this.loadBasic=function(a,b,c){this.basicAutoFit();loadPage(a,b,c)};this.basicAutoFit=function(){var a=document.documentElement.clientHeight;768>a?document.body.style.height="768px":900<a&&document.body.style.height;document.body.style.fontSize="12px"}}
function WdsDisplay(){this.showWdsDlg=function(a,b){closeDialog();g_showAsDialog=!0;showCover(function(a){var d;a=selector("#"+a.id);setCss(a,"opacity",0.2);d=el("div");d.className="LoadConCoverDlg";document.body.appendChild(d);a=el("div");a.className="coverLoadCon";d.appendChild(a);d=el("div");d.id="divWdsDlg";d.className="coverLoadMain";setStyle(d,{background:"none repeat scroll 0% 0% #fcfcfc"});a.appendChild(d);loadPage(b,"divWdsDlg")})};this.closeDialog=function(a){var b=selector("div.LoadConCoverDlg")[0];
null!=b&&(setCss(selector("#"+this.CoverId),"opacity",""),document.body.removeChild(b),hideCover(a),g_showAsDialog=!1)};this.showWdsBegin=function(){!0==g_showAsDialog?showWdsDlg(label.checkingWait,"WlanWDSBegin.htm"):loadPage("WlanWDSBegin.htm","wizardCon")};this.showWdsEnd=function(a){!0==g_showAsDialog?(void 0!=a&&(g_pageEnd=a,g_ifShowEnd=!0),showWdsDlg(label.checkingWait,"WlanWDSEnd.htm")):loadPage("WlanWDSEnd.htm","wizardCon")};this.closeWdsWindow=function(){window.onbeforeunload=null;!0==g_showAsDialog?
(g_homePageUpdate=!0,closeDialog()):($.readNonBlock(SYSTEM_DATA_ID,function(){var a=$.findBlock(SYSTEM_DATA_ID);a.setWzd=1;$.writeNonBlock($.toText(a),$.block)}),loadBasic("Basic.htm","Con",doNothing))}}
function ShowTips(){this.alertTimeHd;this.shAltObjOrId;this.showAlert=function(a,b){var c=id("Error"),d=id("hsErr"),e,f,g;e=document.body;var h=this;!0==isIESix?alert(a):(this.shAltObjOrId=b,f=selector("div.hsTip input")[0],g=selector("span.clacWidth")[0],null==g&&(g=document.createElement("span"),g.className="clacWidth",e.appendChild(g)),g.innerHTML=a,g=g.offsetWidth,null==d&&(d=document.createElement("div"),d.id="hsErr",d.className="hsTip",e=document.createElement("p"),e.className="confirmTitle",
e.innerHTML=label.confirmTitle,d.appendChild(e),e=document.createElement("p"),e.className="detail",d.appendChild(e),f=document.createElement("input"),f.type="button",f.value=btn.ok,f.onclick=function(){h.closeAlert(!0)},e=el("div"),e.className="funcDiv",e.appendChild(f),d.appendChild(e),c.appendChild(d)),e=selector("#hsErr p.detail"),g<e[0].offsetWidth?setCss(e,"textAlign","center"):setCss(e,"textAlign","left"),d.childNodes[1].innerHTML=a,c.style.visibility="visible",c.style.top="90px",f.focus(),
this.alertTimeHd=$.setTimeout(function(){h.closeAlert()},3E4))};this.closeAlert=function(a){var b=id("Error"),c=this.shAltObjOrId;if(null!=b)if(b.style.top="-9999px",b.style.visibility="hidden",clearTimeout(this.alertTimeHd),this.alertTimeHd=null,!0!=a||void 0==c||"object"!=typeof c&&0==c.length)this.shAltObjOrId="";else try{"object"!=typeof c&&(c=id(c)),$.setTimeout(function(){c.select()},200)}catch(d){}};this.shAltBaObjOrId;this.showAlertB=function(a,b){!0==isIESix?alert(a):showCover(function(c){var d;
this.shAltBaObjOrId=b;d=document.createElement("div");d.className="baConfirmCon";document.body.appendChild(d);c=document.createElement("div");c.className="baConfirm";d.appendChild(c);d=document.createElement("i");d.className="baConfirmLogo";c.appendChild(d);d=document.createElement("span");d.className="baConfirmQuestion";d.innerHTML=a;c.appendChild(d);d=document.createElement("input");d.className="subBtn";d.value=btn.confirm;d.type="button";d.onclick=function(){closeAlertB(!0)};c.appendChild(d)})};
this.closeAlertB=function(a){var b=this.shAltBaObjOrId;hideCover(function(){var c=selector("div.baConfirmCon")[0];document.body.removeChild(c);if(!0==a&&void 0!=b&&("object"==typeof b||0!=b.length))try{"object"!=typeof b&&(b=id(b)),b.focus(),b.select()}catch(d){}})};this.phoneShowAlert=function(a,b){showCover(function(){var b,d,e;b=document.createElement("div");b.className="phoneShowCon";d=document.createElement("p");d.className="showStr";d.innerHTML=a;b.appendChild(d);d=document.createElement("div");
d.className="phoneBtnCon";b.appendChild(d);e=document.createElement("input");e.className="phoneAlertOk";e.type="button";e.value=btn.ok;e.onclick=closePhoneShowAlert;d.appendChild(e);d=document.createElement("div");d.id="phoneShowAlertDiv";d.className="phoneShowDiv";d.appendChild(b);document.body.appendChild(d)})};this.closePhoneShowAlert=function(){hideCover(function(){var a=id("phoneShowAlertDiv");document.body.removeChild(a)})};this.showConfirm=function(a,b){var c=id("Confirm"),d=id("hsConf"),e,
f;e=document.body;var g=this,h;!0==isIESix?(c=confirm(a),this.closeConfirm(),b(c)):(f=selector("span.clacWidth")[0],null==f&&(f=document.createElement("span"),f.className="clacWidth",e.appendChild(f)),f.innerHTML=a,f=f.offsetWidth,null==d&&(d=document.createElement("div"),d.id="hsConf",d.className="hsTip",e=document.createElement("p"),e.className="confirmTitle",e.innerHTML=label.confirmTitle,d.appendChild(e),e=document.createElement("p"),e.className="detail",d.appendChild(e),h=el("div"),e=document.createElement("input"),
e.type="button",e.className="cancel",e.value=btn.ok,h.appendChild(e),e=document.createElement("input"),e.type="button",e.className="subBtn",e.value=btn.cancel,h.appendChild(e),d.appendChild(h),c.appendChild(d)),e=selector("#hsConf p.detail"),290>f?setCss(e,"textAlign","center"):setCss(e,"textAlign","left"),f=selector("#hsConf input"),f[0].onclick=function(){g.closeConfirm();b(!0)},f[1].onclick=function(){g.closeConfirm();b(!1)},d.childNodes[1].innerHTML=a,c.style.visibility="visible",c.style.top=
"90px")};this.closeConfirm=function(){var a=id("Confirm");null!=a&&(a.style.top="-9999px",a.style.visibility="hidden")};this.phoneShowConfirm=function(a,b,c,d){showCover(function(){var e,f,g;e=document.createElement("div");e.className="phoneShowCon";f=document.createElement("p");f.className="showStr";f.innerHTML=a;e.appendChild(f);!0==c&&(g=document.createElement("input"),g.className="phoneConfirmInput",g.id="phoneConfirmInput",g.maxLength="32",g.value=d,g.onfocus=function(){document.body.style.paddingBottom=
"40%"},g.onblur=function(){document.body.style.paddingBottom="0"},e.appendChild(g));f=document.createElement("div");f.className="phoneBtnCon";e.appendChild(f);g=document.createElement("input");g.className="phoneConfirmCancel";g.type="button";g.value=btn.cancel;g.onclick=closePhoneShowConfirm;f.appendChild(g);g=document.createElement("input");g.className="phoneConfirmOK";g.type="button";g.value=btn.ok;g.onclick=function(){var a,c;void 0!=(a=id("phoneConfirmInput"))&&(c=a.value);"function"==typeof b&&
b(c);closePhoneShowConfirm()};f.appendChild(g);f=document.createElement("div");f.id="phoneShowConfirmDiv";f.className="phoneShowDiv";f.appendChild(e);document.body.appendChild(f)})};this.closePhoneShowConfirm=function(){hideCover(function(){var a=id("phoneShowConfirmDiv");document.body.removeChild(a)})};this.netSpeedTrans=function(a){return a=1073741824<=a?(a/1073741824).toFixed(1)+"GB/s":1048576<=a?(a/1048576).toFixed(1)+"MB/s":1024<=a?(a/1024).toFixed(1)+"KB/s":a+"B/s"};this.changeLineHeight=function(a){var b,
c="43px",d="0px",e=document.body,f=parseInt(getNodeDefaultView(a,"width"));b=selector("span.clacWidth")[0];null==b&&(b=document.createElement("span"),b.className="clacWidth",e.appendChild(b));b.innerHTML=a.innerHTML;b.offsetWidth>f&&(c="20px",d="1px");a.style.lineHeight=c;a.style.marginTop=d};this.showNote=function(a,b){var c=id(a),d;void 0!=c&&(d=selector("#"+a+" div.noteCon p")[0],void 0!=b&&(d.innerHTML=b),0==d.className.length&&this.changeLineHeight(d),c.style.display=!0==isIESix||!0==isIESeven?
"inline":"inline-block")};this.closeNote=function(a){a=id(a);void 0!=a&&(a.style.display="none")};this.showLoading=function(a,b,c){closeLoading();showCover(function(d){var e,f,g,h,k;e=selector("#"+d.id);var l;g=0;d=!0;!0==g_showAsDialog&&(g=0.2);void 0!=c&&(f=c.loadConClass,h=c.loadClass,k=c.coverLoadingClass,l=c.detailClass,g=c.coverOpacity||g,d="undefined"!=typeof c.bCloseShow?c.bCloseShow:!0);setCss(e,"opacity",g);g=el("div");g.className="LoadConCover";document.body.appendChild(g);e=el("div");
e.className=f||"coverLoadCon";g.appendChild(e);f=el("div");f.className=h||"coverLoad";e.appendChild(f);!0==d&&(h=el("p"),h.className="loadP",d=el("i"),d.className="coverLoadClose",d.onclick=function(){closeLoading(b)},h.appendChild(d),f.appendChild(h));void 0==k?(h=el("img"),h.className="coverLoading",h.src="../images/wdsDetect_me.gif"):(h=el("img"),h.className=k,h.src="../images/wzdWarningWhite_me.png");f.appendChild(h);k=el("p");k.className=l||"coverLoadNote";k.innerHTML=void 0==a?label.checkingWait:
a;f.appendChild(k)})};this.closeLoading=function(a){var b=selector("div.LoadConCover")[0];null!=b&&(document.body.removeChild(b),!0==g_showAsDialog?"function"==typeof a&&a():(setCss(selector("#"+this.CoverId),"opacity",""),hideCover(a)))};this.showProgNumHd;this.showProgressNum=function(a,b,c){var d=this;this.closeProgressNum();showCover(function(e){var f,g,h;e=selector("#"+e.id);var k=a/100,l=0;setCss(e,"opacity",0);setCss(selector("div.hcCo"),"visibility","hidden");e=el("div");e.className="LoadConCover";
document.body.appendChild(e);f=el("div");f.className="coverLoadCon";e.appendChild(f);e=el("div");e.className="coverLoad";f.appendChild(e);f=el("p");f.className="coverLoadNum";g=el("span");g.innerHTML=l;f.appendChild(g);h=el("label");h.innerHTML="%";f.appendChild(h);e.appendChild(f);f=el("p");f.className="coverLoadNumNote";f.innerHTML=void 0==b?statusStr.rebooting:b;e.appendChild(f);(function(){100<l?void 0!=c&&c():(g.innerHTML=l,l++,d.showProgNumHd=$.setTimeout(arguments.callee,k))})()})};this.closeProgressNum=
function(a){var b=selector("div.LoadConCover")[0];null!=b&&(clearTimeout(this.showProgNumHd),setCss(selector("#"+this.CoverId),"opacity",""),setCss(selector("div.hcCo"),"visibility","visible"),document.body.removeChild(b),hideCover(a))};this.debugInfo=function(){for(var a="",b=0,c=arguments.length;b<c;b++)a+=arguments[b]+"\r\n";alert(a)}}
function Select(){this.selectInit=function(a,b,c,d,e){function f(a){for(var b,c,d=a.childNodes,e=0,f=d.length;e<f;e++)c=d[e],b=c.childNodes[0].style.visibility,c.style.backgroundColor="visible"==b?v:y,c.style.color="visible"==b?w:t;a.style.visibility="hidden";a.style.top="-9999px";a.parentNode.style.position="static"}function g(b){var c=id(a),e=b.parentNode,f=e.childNodes,g=selector("#"+a+" span.value")[0];if(3!=b.childNodes[0].nodeType){c.value=b.valueStr;g.value=b.valueStr;for(var h=0,k=f.length;h<
k;h++)f[h].childNodes[0].style.visibility="hidden",f[h].style.backgroundColor=y,f[h].style.color=t;"visible"!=b.childNodes[0].style.visibility&&"undefined"!=typeof d&&d(b.valueStr,c);b.childNodes[0].style.visibility="visible";b.style.backgroundColor=v;b.style.color=w;g.innerHTML=htmlEscape(b.childNodes[1].nodeValue);e.style.visibility="hidden";e.style.top="-9999px";e.parentNode.style.position="static"}}function h(a){for(var b=0,c=a.length;b<c;b++){n=a[b];z=htmlEscape(getStrInMax(n.str.toString(),
A));x="hidden";l=document.createElement("li");if(void 0==n.value&&b==u||u==n.value)x="visible",s.innerHTML=z,s.value=u,m.value=u,l.style.backgroundColor=v,l.style.color=w;l.innerHTML="<span style='visibility:"+x+"'>√</span>"+z;l.title=n.str;l.valueStr=void 0!=n.value?n.value:b;l.className="option";l.style.color=t;l.onclick=function(a){a=a||window.event;g(this);stopProp(a)};l.onmousemove=function(a){a=a||window.event;a=a.srcElement||a.target;var b;if("span"!=a.tagName.toLowerCase()){b=a.parentNode.childNodes;
for(var c=0,d=b.length;c<d;c++)b[c].style.backgroundColor=y,b[c].style.color=t;a.style.backgroundColor=v;a.style.color=w}};r.appendChild(l)}}function k(b){for(var c=selector("#"+p+a),d=selector("ul."+p),e=0;e<d.length;e++)"visible"==d[e].style.visibility&&f(d[e]);setCss(c,"visibility","visible");setCss(c,"top","-1px");c[0].parentNode.style.position="relative";stopProp(b)}var l,n,s,x="hidden",r=document.createElement("ul"),m=id(a),p="selOptsUl",y="#FFFFFF",v="#48b4ff",t="",w="#FFFFFF",q,A,B,z,u=c;
c=m.parentNode;q=selector("#"+a+" span.value");t=getCss(q[0],"color");s=q[0];s.value=0;B=parseInt(getCss(q[0],"width"));q=(0.61*parseInt(getCss(q[0],"fontSize"))).toFixed(1);A=void 0==e?parseInt(B/q):e;m.value=0;r.className=p;r.id=p+a;selector("#"+p+a)[0]||c.appendChild(r);attachEvnt(document.body,"click",function(){var b=selector("#"+p+a)[0];"undefined"!=typeof b&&f(b)});h(b);m.onclick=k;m.disable=function(a){m.onclick=!0==a?null:k;s.style.color=!0==a?"#B2B2B2":"#000000"};m.changeSel=function(b){for(var c=
selector("#"+p+a+" li"),d=0;d<c.length;d++)if(c[d].valueStr==b)return g(c[d]),!1};m.resetOptions=function(a,b){r.innerHTML="";u=b||0;h(a)};b=new NiceScroll(r.id);b.scrollTipOpacity(1);b.scrollTipSet({background:"#999999"});b.init()}}
function Help(){var a=this;this.help="Help";this.helpDetail="helpDetail";this.helpContent="helpContent";this.helpInit=function(){var a=id(this.help),c,d,e=this;null!=a&&(0!=a.innerHTML.length?loadPage("Help.htm",this.helpContent):(c=document.createElement("p"),c.className="helpTop",c.onmousedown=this.draggableBind(this.help),a.appendChild(c),d=document.createElement("span"),d.className="helpDes",d.innerHTML=label.help,c.appendChild(d),d=document.createElement("i"),d.onclick=function(){e.helpClose()},
d.className="helpClose",c.appendChild(d),d=document.createElement("div"),d.id="helpDetail",a.appendChild(d),d=document.createElement("div"),d.style.display="none",d.id=this.helpContent,document.body.appendChild(d),loadPage("Help.htm",this.helpContent),attachEvnt(c,"touchstart",function(a){a=a||window.event;e.mousePos={x:a.touches[0].clientX,y:a.touches[0].clientY};attachEvnt(document,"touchmove",touchMoveHd);attachEvnt(document,"touchend",touchEndHd)})))};this.touchMoveHd=function(b){b=b||window.event;
var c=b.touches[0].clientX,d=b.touches[0].clientY,e=id(a.help),c=c-a.mousePos.x,d=d-a.mousePos.y,f=document.body.clientWidth-e.offsetWidth,g=document.documentElement.scrollHeight-e.offsetHeight,c=0<c?c:0,d=0<d?d:0;e.style.left=(c>f?f:c)+"px";e.style.top=(d>g?g:d)+"px";eventPreventDefault(b);clearSelection(b)};this.touchEndHd=function(a){detachEvnt(document,"touchmove",touchMoveHd);detachEvnt(document,"touchend",touchEndHd)};this.helpBind=function(a,c){a&&(a.onclick=function(a){a=a||window.event;helpShow(c,
a.target||a.srcElement)})};this.helpClose=function(){var a=id(this.help),c=id(this.helpDetail);null!=c&&null!=a&&(setStyle(a,{visibility:"hidden",top:"-9999px",display:"none"}),c.innerHTML="")};this.helpVisible=function(a){var c,d=id(this.help),e=getoffset(a),f=a.offsetHeight;c=a.getAttribute("basicHelpTag");setStyle(d,{display:"block"});a=d.offsetWidth;c=null!=c?selector("#basicSCon")[0]:selector("#hcCo")[0];a=getoffset(c).left+parseInt((c.offsetWidth-a)/2)+"px";setStyle(d,{visibility:"visible",
top:e.top+f+"px",left:a})};this.helpDetailAppend=function(a){var c=id(a);null!=c&&(a=id(this.helpDetail),a.innerHTML=c.outerHTML)};this.helpShow=function(a,c){this.helpClose();this.helpVisible(c);helpDetailAppend(a)};this.msMove=function(a,c,d){var e=c.x-d.x;c=c.y-d.y;d=document.body.clientWidth-a.offsetWidth;var f=document.documentElement.scrollHeight-a.offsetHeight,e=0<e?e:0;c=0<c?c:0;a.style.left=(e>d?d:e)+"px";a.style.top=(c>f?f:c)+"px"};this.draggableBind=function(a){var c=id(a);return function(a){a=
a?a:window.event;a=getMousePos(a);var b={x:a.x-c.offsetLeft,y:a.y-c.offsetTop};document.onmousemove=function(a){a=a?a:window.event;a=getMousePos(a);clearSelection();msMove(c,a,b)};document.onmouseup=function(){clearSelection();document.onmousemove=null;document.onmouseup=null}}}}
function LanDetect(){this.lanDetectSuccess=!1;this.LAN_DETECT_TIME=1E3;this.lanDetectTimeHd=null;this.lanDetectHandle=function(a){!1==$.result.timeout&&!1==this.lanDetectSuccess&&(this.lanDetectSuccess=!0,clearTimeout(this.lanDetectTimeHd),a())};this.lanDetecting=function(a){$.detect(function(){lanDetectHandle(a)});this.lanDetectTimeHd=$.setTimeout(function(){lanDetecting(a)},this.LAN_DETECT_TIME)}}
function Phone(){this.OS={windows:!1,windowsPhone:!1,unixPC:!1,iPad:!1,iPhone:!1,iMacPC:!1,iPod:!1,android:!1,nokia:!1,player:!1,Android_UC:!1,portable:!1,checkDeviceMode:function(){var a=navigator.platform,b=navigator.userAgent;if(void 0!=a)if(0<=a.indexOf("Win"))0<=b.indexOf("Windows Phone")?this.portable=this.windows=this.windowsPhone=!0:(this.windows=!0,this.portable=!1);else if(0<=b.indexOf("NOKIA"))this.portable=this.nokia=!0;else if(0<=b.indexOf("Android"))this.portable=this.android=!0;else if(0<=
a.indexOf("iPad"))this.portable=this.iPad=!0;else if(0<=a.indexOf("iPhone"))this.portable=this.iPhone=!0;else if(0<=a.indexOf("iPod"))this.portable=this.iPod=!0;else if(0<=b.indexOf("Wii")||0<=b.indexOf("PLASTATION"))this.portable=this.player=!0;else if(0<=a.indexOf("Mac"))this.iMacPC=!0,this.portable=!1;else{if(0<=a.indexOf("X11")||0<=a.indexOf("Linux")&&0>a.indexOf("arm"))this.unixPC=!0,this.portable=!1}else 0<=b.indexOf("Android")?this.portable=this.android=!0:this.portable=1024<=document.body.clientWidth||
1024<=document.body.clientHeight?!1:!0}};this.phoneSet={bContinuePCSet:!1};OS.checkDeviceMode()}
function PhonePageNormal(){this.g_showHomeBtn=!0;this.g_ifShowEnd=this.g_showAsDialog=!1;this.g_pageEnd;this.g_ipInfo={ip:"",mask:""};this.apList={apCnt:0,list:[{ssid:"",rssi:"",channel:"",authMode:"",mac:""}]};this.MAX_CONNECTING_TIME=25;this.statusPageSwitch=0;this.androidLanscapeHack=function(a){0<=navigator.userAgent.indexOf("Android")&&(eventAdd(selector("#"+a),"click",function(){if(90==window.orientation||-90==window.orientation){var b=el("div");b.className="android_spacer";document.body.appendChild(b);
document.body.scrollTop=getoffset(selector("#"+a)[0]).top}}),eventAdd(selector("#"+a),"blur",function(){90!=window.orientation&&-90!=window.orientation||removeEl(selector(".android_spacer"))}))};this.adaptCNABrowserInput=function(a){try{"undefined"!=typeof gBeInCNA&&"NOCNA"!=gBeInCNA&&(id(a).onfocus=function(){var a=this,b=a.value;a.value="";a.type="password";$.setTimeout(function(){a.type="text";a.value=b},0)})}catch(b){}}}
function Profile(){this.sendAddInstr=function(a,b,c,d,e,f){a=" cSsid:"+encodeBlankspace(a);b=" cBridgedSsid:"+encodeBlankspace(b);c=" cBridgedBssid:"+c;d=" uSecurityType:"+d;e=" cPassWD:"+encodeBlankspace(e);$.instr("wlan profile -add"+a+b+c+" uWepIndex:1"+d+e,function(a){"function"==typeof f&&f(a.errorno)})}}
(function(){window.jQuery=window.$=function(){};Phone.call(window);Tool.call(window);PageFunc.call(window);Cover.call(window);Explorer.call(window);LocalStorageSD.call(window);HighSet.call(window);Basic.call(window);PhonePageNormal.call(window);ShowTips.call(window);Select.call(window);LanDetect.call(window);Help.call(window);Profile.call(window);WdsDisplay.call(window)})();
